export const JAPANESE_CHARACTER_STROKES = [
  { character: "あ", name: "a", type: "hiragana", strokeCount: 3 },
  { character: "い", name: "i", type: "hiragana", strokeCount: 2 },
  { character: "う", name: "u", type: "hiragana", strokeCount: 2 },
  { character: "え", name: "e", type: "hiragana", strokeCount: 2 },
  { character: "お", name: "o", type: "hiragana", strokeCount: 3 },
  { character: "か", name: "ka", type: "hiragana", strokeCount: 3 },
  { character: "き", name: "ki", type: "hiragana", strokeCount: 4 },
  { character: "く", name: "ku", type: "hiragana", strokeCount: 1 },
  { character: "け", name: "ke", type: "hiragana", strokeCount: 3 },
  { character: "こ", name: "ko", type: "hiragana", strokeCount: 2 },
  { character: "さ", name: "sa", type: "hiragana", strokeCount: 3 },
  { character: "し", name: "shi", type: "hiragana", strokeCount: 1 },
  { character: "す", name: "su", type: "hiragana", strokeCount: 2 },
  { character: "せ", name: "se", type: "hiragana", strokeCount: 3 },
  { character: "そ", name: "so", type: "hiragana", strokeCount: 1 },
  { character: "た", name: "ta", type: "hiragana", strokeCount: 4 },
  { character: "ち", name: "chi", type: "hiragana", strokeCount: 2 },
  { character: "つ", name: "tsu", type: "hiragana", strokeCount: 1 },
  { character: "て", name: "te", type: "hiragana", strokeCount: 1 },
  { character: "と", name: "to", type: "hiragana", strokeCount: 2 },
  { character: "な", name: "na", type: "hiragana", strokeCount: 4 },
  { character: "に", name: "ni", type: "hiragana", strokeCount: 3 },
  { character: "ぬ", name: "nu", type: "hiragana", strokeCount: 2 },
  { character: "ね", name: "ne", type: "hiragana", strokeCount: 4 },
  { character: "の", name: "no", type: "hiragana", strokeCount: 1 },
  { character: "は", name: "ha", type: "hiragana", strokeCount: 3 },
  { character: "ひ", name: "hi", type: "hiragana", strokeCount: 1 },
  { character: "ふ", name: "fu", type: "hiragana", strokeCount: 4 },
  { character: "へ", name: "he", type: "hiragana", strokeCount: 1 },
  { character: "ほ", name: "ho", type: "hiragana", strokeCount: 4 },
  { character: "ま", name: "ma", type: "hiragana", strokeCount: 3 },
  { character: "み", name: "mi", type: "hiragana", strokeCount: 2 },
  { character: "む", name: "mu", type: "hiragana", strokeCount: 3 },
  { character: "め", name: "me", type: "hiragana", strokeCount: 2 },
  { character: "も", name: "mo", type: "hiragana", strokeCount: 3 },
  { character: "や", name: "ya", type: "hiragana", strokeCount: 3 },
  { character: "ゆ", name: "yu", type: "hiragana", strokeCount: 2 },
  { character: "よ", name: "yo", type: "hiragana", strokeCount: 2 },
  { character: "ら", name: "ra", type: "hiragana", strokeCount: 2 },
  { character: "り", name: "ri", type: "hiragana", strokeCount: 2 },
  { character: "る", name: "ru", type: "hiragana", strokeCount: 1 },
  { character: "れ", name: "re", type: "hiragana", strokeCount: 2 },
  { character: "ろ", name: "ro", type: "hiragana", strokeCount: 1 },
  { character: "わ", name: "wa", type: "hiragana", strokeCount: 2 },
  { character: "を", name: "wo", type: "hiragana", strokeCount: 3 },
  { character: "ん", name: "n", type: "hiragana", strokeCount: 1 },
  { character: "ア", name: "a", type: "katakana", strokeCount: 2 },
  { character: "イ", name: "i", type: "katakana", strokeCount: 2 },
  { character: "ウ", name: "u", type: "katakana", strokeCount: 3 },
  { character: "エ", name: "e", type: "katakana", strokeCount: 3 },
  { character: "オ", name: "o", type: "katakana", strokeCount: 3 },
  { character: "カ", name: "ka", type: "katakana", strokeCount: 2 },
  { character: "キ", name: "ki", type: "katakana", strokeCount: 3 },
  { character: "ク", name: "ku", type: "katakana", strokeCount: 2 },
  { character: "ケ", name: "ke", type: "katakana", strokeCount: 3 },
  { character: "コ", name: "ko", type: "katakana", strokeCount: 2 },
  { character: "サ", name: "sa", type: "katakana", strokeCount: 3 },
  { character: "シ", name: "shi", type: "katakana", strokeCount: 3 },
  { character: "ス", name: "su", type: "katakana", strokeCount: 2 },
  { character: "セ", name: "se", type: "katakana", strokeCount: 2 },
  { character: "ソ", name: "so", type: "katakana", strokeCount: 2 },
  { character: "タ", name: "ta", type: "katakana", strokeCount: 3 },
  { character: "チ", name: "chi", type: "katakana", strokeCount: 3 },
  { character: "ツ", name: "tsu", type: "katakana", strokeCount: 3 },
  { character: "テ", name: "te", type: "katakana", strokeCount: 3 },
  { character: "ト", name: "to", type: "katakana", strokeCount: 2 },
  { character: "ナ", name: "na", type: "katakana", strokeCount: 2 },
  { character: "ニ", name: "ni", type: "katakana", strokeCount: 2 },
  { character: "ヌ", name: "nu", type: "katakana", strokeCount: 2 },
  { character: "ネ", name: "ne", type: "katakana", strokeCount: 4 },
  { character: "ノ", name: "no", type: "katakana", strokeCount: 1 },
  { character: "ハ", name: "ha", type: "katakana", strokeCount: 2 },
  { character: "ヒ", name: "hi", type: "katakana", strokeCount: 2 },
  { character: "フ", name: "fu", type: "katakana", strokeCount: 1 },
  { character: "ヘ", name: "he", type: "katakana", strokeCount: 1 },
  { character: "ホ", name: "ho", type: "katakana", strokeCount: 4 },
  { character: "マ", name: "ma", type: "katakana", strokeCount: 2 },
  { character: "ミ", name: "mi", type: "katakana", strokeCount: 3 },
  { character: "ム", name: "mu", type: "katakana", strokeCount: 2 },
  { character: "メ", name: "me", type: "katakana", strokeCount: 2 },
  { character: "モ", name: "mo", type: "katakana", strokeCount: 3 },
  { character: "ヤ", name: "ya", type: "katakana", strokeCount: 2 },
  { character: "ユ", name: "yu", type: "katakana", strokeCount: 2 },
  { character: "ヨ", name: "yo", type: "katakana", strokeCount: 3 },
  { character: "ラ", name: "ra", type: "katakana", strokeCount: 2 },
  { character: "リ", name: "ri", type: "katakana", strokeCount: 2 },
  { character: "ル", name: "ru", type: "katakana", strokeCount: 2 },
  { character: "レ", name: "re", type: "katakana", strokeCount: 1 },
  { character: "ロ", name: "ro", type: "katakana", strokeCount: 3 },
  { character: "ワ", name: "wa", type: "katakana", strokeCount: 2 },
  { character: "ヲ", name: "wo", type: "katakana", strokeCount: 3 },
  { character: "ン", name: "n", type: "katakana", strokeCount: 2 },
  { character: "日", name: "sun / day", type: "kanji", strokeCount: 4, pronunciation: "nichi / jitsu / hi / bi / ka", translation: "sun, day", readings: { on: ["nichi", "jitsu"], kun: ["hi", "bi", "ka"] } },
  { character: "月", name: "moon / month", type: "kanji", strokeCount: 4, pronunciation: "getsu / gatsu / tsuki", translation: "moon, month", readings: { on: ["getsu", "gatsu"], kun: ["tsuki"] } },
  { character: "火", name: "fire", type: "kanji", strokeCount: 4, pronunciation: "ka / hi", translation: "fire", readings: { on: ["ka"], kun: ["hi"] } },
  { character: "水", name: "water", type: "kanji", strokeCount: 4, pronunciation: "sui / mizu", translation: "water", readings: { on: ["sui"], kun: ["mizu"] } },
  { character: "木", name: "tree", type: "kanji", strokeCount: 4, pronunciation: "moku / boku / ki / ko", translation: "tree, wood", readings: { on: ["moku", "boku"], kun: ["ki", "ko"] } },
  { character: "金", name: "gold", type: "kanji", strokeCount: 8, pronunciation: "kin / kon / kane", translation: "gold, money, metal", readings: { on: ["kin", "kon"], kun: ["kane", "kana"] } },
  { character: "土", name: "earth", type: "kanji", strokeCount: 3, pronunciation: "do / to / tsuchi", translation: "earth, soil", readings: { on: ["do", "to"], kun: ["tsuchi"] } },
  { character: "山", name: "mountain", type: "kanji", strokeCount: 3, pronunciation: "san / yama", translation: "mountain", readings: { on: ["san"], kun: ["yama"] } },
  { character: "川", name: "river", type: "kanji", strokeCount: 3, pronunciation: "sen / kawa", translation: "river", readings: { on: ["sen"], kun: ["kawa"] } },
  { character: "田", name: "rice field", type: "kanji", strokeCount: 5, pronunciation: "den / ta", translation: "rice field", readings: { on: ["den"], kun: ["ta"] } },
  { character: "人", name: "person", type: "kanji", strokeCount: 2, pronunciation: "jin / nin / hito", translation: "person", readings: { on: ["jin", "nin"], kun: ["hito"] } },
  { character: "口", name: "mouth", type: "kanji", strokeCount: 3, pronunciation: "kou / ku / kuchi", translation: "mouth", readings: { on: ["kou", "ku"], kun: ["kuchi"] } },
  { character: "目", name: "eye", type: "kanji", strokeCount: 5, pronunciation: "moku / boku / me", translation: "eye", readings: { on: ["moku", "boku"], kun: ["me", "ma"] } },
  { character: "耳", name: "ear", type: "kanji", strokeCount: 6, pronunciation: "ji / mimi", translation: "ear", readings: { on: ["ji"], kun: ["mimi"] } },
  { character: "手", name: "hand", type: "kanji", strokeCount: 4, pronunciation: "shu / te", translation: "hand", readings: { on: ["shu"], kun: ["te", "ta"] } },
  { character: "足", name: "foot", type: "kanji", strokeCount: 7, pronunciation: "soku / ashi / ta", translation: "foot, leg, enough", readings: { on: ["soku"], kun: ["ashi", "ta"] } },
  { character: "心", name: "heart", type: "kanji", strokeCount: 4, pronunciation: "shin / kokoro", translation: "heart, mind", readings: { on: ["shin"], kun: ["kokoro"] } },
  { character: "力", name: "power", type: "kanji", strokeCount: 2, pronunciation: "ryoku / riki / chikara", translation: "power, strength", readings: { on: ["ryoku", "riki"], kun: ["chikara"] } },
  { character: "学", name: "study", type: "kanji", strokeCount: 8, pronunciation: "gaku / mana", translation: "study, learning", readings: { on: ["gaku"], kun: ["mana"] } },
  { character: "先", name: "ahead", type: "kanji", strokeCount: 6, pronunciation: "sen / saki", translation: "ahead, previous, tip", readings: { on: ["sen"], kun: ["saki"] } },
  { character: "生", name: "life", type: "kanji", strokeCount: 5, pronunciation: "sei / shou / i / u / nama", translation: "life, birth, raw", readings: { on: ["sei", "shou"], kun: ["i", "u", "nama"] } },
  { character: "大", name: "big", type: "kanji", strokeCount: 3, pronunciation: "dai / tai / oo", translation: "big, large", readings: { on: ["dai", "tai"], kun: ["oo"] } },
  { character: "小", name: "small", type: "kanji", strokeCount: 3, pronunciation: "shou / chii / ko / o", translation: "small, little", readings: { on: ["shou"], kun: ["chii", "ko", "o"] } },
  { character: "中", name: "middle", type: "kanji", strokeCount: 4, pronunciation: "chuu / naka", translation: "middle, inside", readings: { on: ["chuu"], kun: ["naka"] } },
  { character: "上", name: "up", type: "kanji", strokeCount: 3, pronunciation: "jou / ue / a / nobo", translation: "up, above", readings: { on: ["jou"], kun: ["ue", "a", "nobo"] } },
  { character: "下", name: "down", type: "kanji", strokeCount: 3, pronunciation: "ka / ge / shita / sa / kuda", translation: "down, below", readings: { on: ["ka", "ge"], kun: ["shita", "sa", "kuda"] } }
];
